<a href="https://colab.research.google.com/github/Ron-Wu/Machine-learning-0602/blob/main/01_RNN_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
from tensorflow.keras import layers, models

In [2]:
# Sample: 1
# Sequence Length: 5
# feature dimension: 8

inputs = tf.random.normal([1, 5, 8])

# tf.keras.layers.LSTM

In [5]:
# output = layers.LSTM(units=3)(inputs)
output = layers.LSTM(units=3, return_sequences=True)(inputs)
print(output.shape)

(1, 5, 3)


In [4]:
whole_seq_output, final_hiden_state, final_cell_state = layers.LSTM(3, 
                                                                    return_sequences=True, # True:得到每個時間點的output 
                                                                    return_state=True)(inputs) # True:最後一個時間點的h, c

print('whole_seq_output: ', whole_seq_output.shape, whole_seq_output)
print('final_hiden_state (h): ', final_hiden_state.shape, final_hiden_state)
print('final_cell_state (c): ', final_cell_state.shape, final_cell_state)

whole_seq_output:  (1, 5, 3) tf.Tensor(
[[[ 0.20320845  0.0868627   0.08685748]
  [ 0.36432424  0.3584084   0.19488938]
  [-0.02568113  0.2051757   0.2679192 ]
  [ 0.26185203  0.4415762   0.19969772]
  [ 0.02701587  0.04609432  0.17912824]]], shape=(1, 5, 3), dtype=float32)
final_hiden_state (h):  (1, 3) tf.Tensor([[0.02701587 0.04609432 0.17912824]], shape=(1, 3), dtype=float32)
final_cell_state (c):  (1, 3) tf.Tensor([[0.09608124 0.21627405 0.20318986]], shape=(1, 3), dtype=float32)


# tf.keras.layers.GRU

In [6]:
output = layers.GRU(units=3)(inputs)
print(output.shape)

(1, 3)


In [7]:
# output 沒有 c
whole_sequence_output, final_state = layers.GRU(3, return_sequences=True, return_state=True)(inputs)

print('whole_seq_output: ', whole_sequence_output.shape, whole_sequence_output)
print('final_state (h): ', final_state.shape, final_state)

whole_seq_output:  (1, 5, 3) tf.Tensor(
[[[-0.17894605  0.6080384  -0.12286589]
  [-0.6290288   0.6598771  -0.04857271]
  [-0.31789404  0.05393986  0.24701616]
  [-0.4966442   0.3179363  -0.62757695]
  [ 0.1526277   0.46977273 -0.70959246]]], shape=(1, 5, 3), dtype=float32)
final_state (h):  (1, 3) tf.Tensor([[ 0.1526277   0.46977273 -0.70959246]], shape=(1, 3), dtype=float32)


# tf.keras.layers.Bidirectional

In [8]:
output = layers.Bidirectional(layers.LSTM(3))(inputs)
print(output.shape) # 因為順向（3）加逆向（3）

(1, 6)


In [9]:
# merge_mode: Sum
output = layers.Bidirectional(layers.LSTM(3), merge_mode='sum')(inputs)
print(output.shape)

(1, 3)


In [10]:
# return_sequences: True
output = layers.Bidirectional(layers.LSTM(10, return_sequences=True))(inputs)
print(output.shape)

(1, 5, 20)


In [11]:
# return_sequences: True, 
output, forward_h, forward_c, backward_h, backward_c = layers.Bidirectional(layers.LSTM(2, return_sequences=True, return_state=True))(inputs)
print('output : ', output.shape, output)
print('forward_h : ', forward_h.shape, forward_h)
print('forward_c : ', forward_c.shape, forward_c)
print('backward_h : ', backward_h.shape, backward_h)
print('backward_c : ', backward_c.shape, backward_c)


output :  (1, 5, 4) tf.Tensor(
[[[ 0.00767907 -0.03574024 -0.1429682  -0.27382717]
  [-0.06311151 -0.12624612  0.02876142 -0.08537212]
  [-0.15491545 -0.09852992  0.21898209  0.05458275]
  [-0.09643558 -0.11551264 -0.00779475 -0.11317746]
  [ 0.3699543  -0.00553183  0.38291797  0.14241624]]], shape=(1, 5, 4), dtype=float32)
forward_h :  (1, 2) tf.Tensor([[ 0.3699543  -0.00553183]], shape=(1, 2), dtype=float32)
forward_c :  (1, 2) tf.Tensor([[ 0.4188828  -0.03246808]], shape=(1, 2), dtype=float32)
backward_h :  (1, 2) tf.Tensor([[-0.1429682  -0.27382717]], shape=(1, 2), dtype=float32)
backward_c :  (1, 2) tf.Tensor([[-0.45263442 -0.66950417]], shape=(1, 2), dtype=float32)


## Many-to-one

In [ ]:
input = layers.Input(shape=(5, 8))
x = layers.LSTM(2)(input)
ouput = layers.Dense(10, activation='softmax')(x)
model = models.Model(input, ouput)
model.summary()

Model: "model_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         [(None, 5, 8)]            0         
_________________________________________________________________
lstm_7 (LSTM)                (None, 2)                 88        
_________________________________________________________________
dense_2 (Dense)              (None, 10)                30        
Total params: 118
Trainable params: 118
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# multi-layer
input = layers.Input(shape=(5, 8))
x1 = layers.LSTM(128, return_sequences=True)(input)
x2 = layers.LSTM(256, return_sequences=True)(x1)
x3 = layers.LSTM(10)(x2)
ouput = layers.Dense(10, activation='softmax')(x3)
model = models.Model(input, ouput)
model.summary()

Model: "functional_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_5 (InputLayer)         [(None, 5, 8)]            0         
_________________________________________________________________
lstm_20 (LSTM)               (None, 5, 128)            70144     
_________________________________________________________________
lstm_21 (LSTM)               (None, 5, 256)            394240    
_________________________________________________________________
lstm_22 (LSTM)               (None, 10)                10680     
_________________________________________________________________
dense_3 (Dense)              (None, 10)                110       
Total params: 475,174
Trainable params: 475,174
Non-trainable params: 0
_________________________________________________________________


# Many-to-many (same length)

In [ ]:
input = layers.Input(shape=(50, 8))
x = layers.LSTM(10, return_sequences=True)(input)
output = layers.Dense(20, activation='softmax')(x)
# output = layers.TimeDistributed(layers.Dense(20, activation='softmax'))(x)
model = models.Model(input, output)
model.summary()

Model: "functional_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_6 (InputLayer)         [(None, 50, 8)]           0         
_________________________________________________________________
lstm_23 (LSTM)               (None, 50, 10)            760       
_________________________________________________________________
dense_4 (Dense)              (None, 50, 20)            220       
Total params: 980
Trainable params: 980
Non-trainable params: 0
_________________________________________________________________


## Many-to-many (different length) : Seq2seq

In [ ]:
input = layers.Input(shape=(50, 16))
x = layers.LSTM(1)(input)
model = models.Model(input, x)
model.summary()

Model: "functional_17"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_10 (InputLayer)        [(None, 50, 16)]          0         
_________________________________________________________________
lstm_27 (LSTM)               (None, 1)                 72        
Total params: 72
Trainable params: 72
Non-trainable params: 0
_________________________________________________________________
